#!/usr/bin/env python3
"""Regenerate index.json, the README runs table and the root SHA256SUMS from the run.json files.

`add_run.py` does this after recording a run; a commit that only touches tools/ has no run to
add, yet the root manifest covers every tracked file, so it must be regenerated by hand:

    python3 tools/regenerate.py            # then python3 tools/verify.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import record  # noqa: E402


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--root", type=Path, default=HERE.parent, help="repository root (default: parent of tools/)")
    a = ap.parse_args(argv)
    try:
        record.regenerate(a.root)
    except OSError as e:
        raise SystemExit(f"cannot regenerate the record at {a.root}: {e}") from e
    print(f"regenerated index.json, README table and SHA256SUMS under {a.root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
